"""campaign and post changes

Revision ID: 12fdb48401bf
Revises: 5f94e7be5bdc
Create Date: 2025-07-15 12:35:26.930412

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "12fdb48401bf"
down_revision: Union[str, Sequence[str], None] = "5f94e7be5bdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
