"""empty message

Revision ID: 39b41296563e
Revises: 12fdb48401bf
Create Date: 2025-07-16 10:48:19.745925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39b41296563e"
down_revision: Union[str, Sequence[str], None] = "12fdb48401bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("external", sa.String(length=255), nullable=True))
    op.add_column("posts", sa.Column("date", sa.DateTime(), nullable=False))
    op.drop_column("posts", "external_keyword")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "external_keyword",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("posts", "date")
    op.drop_column("posts", "external")
    # ### end Alembic commands ###
