"""post changes

Revision ID: 47ae07687240
Revises: c35e68c52dbb
Create Date: 2025-07-15 12:29:15.767014

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47ae07687240"
down_revision: Union[str, Sequence[str], None] = "c35e68c52dbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("conclusions_urls", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "posts", sa.Column("citys_urls", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "posts", sa.Column("external_keyword", sa.String(length=255), nullable=True)
    )
    op.add_column("posts", sa.Column("hastags", sa.String(length=255), nullable=True))
    op.alter_column(
        "posts", "seo_title", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "posts", "keywords", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "posts", "keywords_urls", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "posts", "conclusions", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "posts", "citys", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "posts", "external_url", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "posts", "slug", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "posts", "categories", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "posts", "language", existing_type=sa.VARCHAR(length=10), nullable=True
    )
    op.drop_constraint(op.f("posts_slug_key"), "posts", type_="unique")
    op.drop_column("posts", "external")
    op.drop_column("posts", "hashtags")
    op.drop_column("posts", "status")
    op.drop_column("posts", "conclusion_urls")
    op.drop_column("posts", "city_urls")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "city_urls", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "posts",
        sa.Column(
            "conclusion_urls",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "posts", sa.Column("status", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "posts",
        sa.Column(
            "hashtags", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "posts",
        sa.Column(
            "external", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.create_unique_constraint(
        op.f("posts_slug_key"), "posts", ["slug"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "posts", "language", existing_type=sa.VARCHAR(length=10), nullable=False
    )
    op.alter_column(
        "posts", "categories", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "posts", "slug", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "posts", "external_url", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "posts", "citys", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "posts", "conclusions", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "posts", "keywords_urls", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "posts", "keywords", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "posts", "seo_title", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("posts", "hastags")
    op.drop_column("posts", "external_keyword")
    op.drop_column("posts", "citys_urls")
    op.drop_column("posts", "conclusions_urls")
    # ### end Alembic commands ###
