"""little corrections

Revision ID: 532b55938ce2
Revises: 1aa77355e348
Create Date: 2025-07-14 11:41:25.087336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "532b55938ce2"
down_revision: Union[str, Sequence[str], None] = "1aa77355e348"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("categories", sa.String(length=255), nullable=False)
    )
    op.drop_column("posts", "categoties")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "categoties", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("posts", "categories")
    # ### end Alembic commands ###
