"""post changes

Revision ID: 5f94e7be5bdc
Revises: 47ae07687240
Create Date: 2025-07-15 12:32:05.542956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f94e7be5bdc"
down_revision: Union[str, Sequence[str], None] = "47ae07687240"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("status", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "status")
    # ### end Alembic commands ###
