"""optimize

Revision ID: 64efec3fe5fa
Revises: f3a773fc5be4
Create Date: 2025-07-26 12:25:32.887676

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '64efec3fe5fa'
down_revision: Union[str, Sequence[str], None] = 'f3a773fc5be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
