"""Post little adjusts

Revision ID: 8b0c28e34f57
Revises: 39b41296563e
Create Date: 2025-07-16 17:05:49.698628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b0c28e34f57"
down_revision: Union[str, Sequence[str], None] = "39b41296563e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("hashtags", sa.String(length=255), nullable=True))
    op.drop_column("posts", "hastags")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "hastags", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("posts", "hashtags")
    # ### end Alembic commands ###
