"""optimize

Revision ID: a8351f657dae
Revises: 64efec3fe5fa
Create Date: 2025-07-26 12:34:51.515370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8351f657dae'
down_revision: Union[str, Sequence[str], None] = '64efec3fe5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimized_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('keywords_urls', sa.String(length=255), nullable=True),
    sa.Column('conclusions', sa.Text(), nullable=True),
    sa.Column('conclusions_urls', sa.Text(), nullable=True),
    sa.Column('citys', sa.Text(), nullable=True),
    sa.Column('citys_urls', sa.Text(), nullable=True),
    sa.Column('external', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('edition_url', sa.String(length=255), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimized_posts_id'), 'optimized_posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimized_posts_id'), table_name='optimized_posts')
    op.drop_table('optimized_posts')
    # ### end Alembic commands ###
