"""Post little adjusts

Revision ID: c27f24abe513
Revises: 8b0c28e34f57
Create Date: 2025-07-16 17:07:26.675079

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c27f24abe513"
down_revision: Union[str, Sequence[str], None] = "8b0c28e34f57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
