"""campaign modification

Revision ID: c35e68c52dbb
Revises: 532b55938ce2
Create Date: 2025-07-15 11:38:38.599886

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c35e68c52dbb"
down_revision: Union[str, Sequence[str], None] = "532b55938ce2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaigns", sa.Column("email", sa.String(), nullable=False))
    op.add_column("campaigns", sa.Column("password", sa.String(), nullable=False))
    op.drop_column("campaigns", "_email")
    op.drop_column("campaigns", "_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns",
        sa.Column("_password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "campaigns",
        sa.Column("_email", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("campaigns", "password")
    op.drop_column("campaigns", "email")
    # ### end Alembic commands ###
