"""slug removed from optimize

Revision ID: e3b221c9d0c7
Revises: a8351f657dae
Create Date: 2025-07-28 11:09:53.653312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b221c9d0c7'
down_revision: Union[str, Sequence[str], None] = 'a8351f657dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('optimized_posts', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('optimized_posts', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
