INSTAGRAM_MADURACION_CAPABILITY = "instagram.maduracion"
INSTAGRAM_PROSPECTING_CAPABILITY = "instagram.prospecting"

INSTAGRAM_CAPABILITIES = frozenset(
    {
        INSTAGRAM_MADURACION_CAPABILITY,
        INSTAGRAM_PROSPECTING_CAPABILITY,
    }
)
